### PR TITLE
Added custom types for item_id and originator_id

### PR DESCRIPTION
**Pull request by narrowtux**
Needed the same thing as #14, found a fairly elegant solution IMHO. 

Using `Application.get_env`, the type in the schema can be overwritten at compile time.

You still need to edit the types in the generated migration, this is documented in the README.

### CODE REVIEW

**Comment by izelnakri** [comment]
Thank you for a very interesting PR! Could you write tests as well?

**Comment by narrowtux** [comment]
I should definitely write some tests but it's a huge effort since the database structure is different. Maybe I can reuse the existing tests and introduce a variable to switch from `:integer` to `Ecto.UUID` and just test the normal tests twice.

**Comment by drapergeek** [comment]
Thank you so much for implementing this! I just ran into this exact same issue, I'd love to be able to use this feature!

**Comment by narrowtux** [comment]
You can test this by changing 

`{:paper_trail, "~> 0.7.3"}` to `{:paper_trail, github: "narrowtux/paper_trail"}` in your `mix.exs`.

**Comment by drapergeek** [comment]
Thanks, already on it. I'll let you know if I run into any issues.

**Comment by drapergeek** [comment]
This works great for me, just wanted to put a 👍 on here for getting this into hex.

**Comment by izelnakri** [comment]
thank you once again for your contribution @narrowtux. I discourage using github based packages for production, its ok for testing something. 

I'm willing to merge this if there were well written throughout tests like we have for hash bang functions, strict mode etc. If you would this to be merged soon please do not hesitate to contribute! Otherwise I dont know when I will find the time to write them for you guys, currently Im very busy.

**Pull request merged**
