### PR TITLE
Adding index

### PR DESCRIPTION
**Pull request by asiniy**

### CODE REVIEW

**Comment by izelnakri** [comment]
I think we can add this as an actual comment :D 👍
```elixir
# Uncomment if you want to add the following indexes to speed up special queries:
# create index(:versions, [:event, :item_id, :item_type])
```

**Comment by asiniy** [comment]
@izelnakri I can't get the purpose of this commenting out. Why do we need it?

**Comment by izelnakri** [comment]
having indexes on those fields is a great idea however some people might not need them or need them differently, having that index has a small speed con if its not needed. 

By putting a comment warning we can explicitly state that that part of the functionality is optional. Normally I like self-documenting/no-comments code however for this case I think it suits better if we have comments.

**Comment by asiniy** [comment]
@izelnakri done

**Pull request merged**
