### PR TITLE
Expose PapertTrail Multi Functions

### LINKED ISSUE #128: Unclear how to use `PaperTrail.Multi`.
We're trying to integrate PaperTrail in our application, which uses Ecto.Multi quite extensively.
We've tried many different combinations of `PaperTrail.Multi.new()`, then adding steps using the standard `Ecto.Multi.insert` and / or `Ecto.Multi.update` functions, then trying to commit using `PaperTrail.Multi.commit` but it doesn't seem to work.
We've noticed that `PaperTrail.Multi.insert` and `PaperTrail.Multi.update` exist, but we are confused on the exposed API here - these two don't expose a "step name" for example - so we're not sure whether they're drop-in replacement or wrappers, and how to use them.

It would be great if someone could indicate how to use `PaperTrail` with `Multi` - or maybe add tests so that we could understand?

So far, the only solution we found would be to replace all our calls to `Multi.update` / `Multi.insert` by `Multi.run` wrapping `PaperTrail.*` equivalents... Is it the way to go?

### PR DESCRIPTION
**Pull request by maennchen**
Based on #131, merge that PR first.

Really exposes Multi implementation so that multiple resources can be persisted at once.

Closes #128 

## Deprecations / Reasons

* `PaperTrail.Multi.insert` Option `model_key` - Since the function now takes a `name` (aligned with `Ecto.Multi`), the option is no longer needed.
* `PaperTrail.Multi.insert` Option `version_key` - Since the function now takes a `name` (aligned with `Ecto.Multi`), the option is no longer needed.

### CODE REVIEW

**Comment by maennchen** [comment]
@hickscorp Could I get your feedback on this?

**Comment by izelnakri** [comment]
Hi @maennchen, could you write a test a case that asserts/shows your proposed solution? 

It is currently very difficult for me to see what we are trying to accomplish, I see many changes, deprecations etc. Thank you for seperating them to 2 PRs but each will need descriptions/explanation of the motivation. 

Also thanks for taking a stab at this, I'd really like to understand what is currently being proposed in code, and why deprecations were necessary. `paper_trail` is now getting thousands of downloads every week so we need to be very careful with the changes we review/introduce/merge. Thanks!

**Comment by maennchen** [comment]
@izelnakri I've added a test that shows how the `PaperTrail.Multi` functions can be used. The description of this PR now contains a list of deprecations and their motivation.

**Comment by hickscorp** [comment]
@maennchen I like that things are getting documented with the multi usage. If you manage to get this PR merged, I think it will make it easier to then be able to refactor PaperTrail into a "drop-in" replacement for `Ecto.Repo` like I suggested in another comment.
A few things we discovered were impossible with PaperTrail:

- Work with models that have a composite primary key (Eg - join tables for many-to-many).
- Work in mixed Int / UUID environments.

But I think we could discuss this in a dedicated issue / PR?

**Comment by izelnakri** [comment]
Hi @hickscorp yes I would appreciate a separate PR for each proposed solutions(and ideally making them independent and well tested). So we can merge things even without any deprecations. That would be even better, thanks!

**Comment by maennchen** [comment]
@izelnakri Is there anything I should do on those two PRs? Do you agree with how I did it? If not: where / why / what would you change?

**Comment by maennchen** [comment]
@izelnakri ping

**Comment by izelnakri** [comment]
> yes I would appreciate a separate PR for each proposed solution(and ideally making them independent from each other and well tested). So we can merge things even without any deprecations.

**Comment by maennchen** [comment]
@izelnakri I will not untangle this PR. I made the decision to base those on top of each other on purpose because it creates a lot of merge conflicts if I would not do that.

I'd rather solve #131 first and then rebase this one.

**Comment by maennchen** [comment]
@izelnakri Tests for this change have been added.

**Comment by izelnakri** [comment]
> @izelnakri I will not untangle this PR. I made the decision to base those on top of each other on purpose because it creates a lot of merge conflicts if I would not do that.
> 
> I'd rather solve #131 first and then rebase this one.

We need to adhere to certain process and quality requirements atm @maennchen, this pkg received more than 200k downloads and its growing, so we need to take into account the users of this package ensure they have a smooth upgrade process.

This means deprecations have to be handled differently even if it means rework/extra work.

Also, despite my extreme busyness last month I try to review your contributions on time so please dont threathen to not contribute etc we appreciate your contributions :)

I dont have actually any requirement to even accept contributions let alone reviewing, just speaking hypothetically, of course we all want to improve the codebase. However at this stage improvements have to adhere to certain requirements, whether we like it or not. Thanks for you contributions so far, I’m always looking forward to them ! ;)

**Comment by maennchen** [comment]
@izelnakri I don't want to come off threatening at all and I would like to improve this project.

This includes depredations as well. I also don't want to say that all my decisions are correct, but I would at least like to be able to talk about all the steps I took. Currently it seemed to me as a categorical "no" instead of analyzing what is needed and what is not.

Especially for a well received library, I think it's important to make public / private functions clear. The path I took in the PR was very careful to not introduce breaking changes but instead provide clear deprecations so that people have it easy to upgrade in the future as well.

**Comment by izelnakri** [comment]
> @izelnakri I don't want to come off threatening at all and I would like to improve this project.
> 
> This includes depredations as well. I also don't want to say that all my decisions are correct, but I would at least like to be able to talk about all the steps I took. Currently it seemed to me as a categorical "no" instead of analyzing what is needed and what is not.
> 
> Especially for a well received library, I think it's important to make public / private functions clear. The path I took in the PR was very careful to not introduce breaking changes but instead provide clear deprecations so that people have it easy to upgrade in the future as well.

All clear @maennchen , part of software development is subjective opinions and we could also have disagreements. I'd like to discuss find the right solutions as much as you do. Almost all public API atm is either intentionally made or reviewed, so each needs its own discussion and any change/improvement we make should depend on deprecations. 

Therefore, please "Expose PaperTrail.Multi Functions" without any dependency on deprecations. We can discuss deprecations separately. Hope you're having a good weekend, thanks! :)

**Comment by maennchen** [comment]
@izelnakri I'm sorry, but this is not how I would like to contribute to this project.

I will therefore close my PRs. Feel free to take anything from them as you wish.

**Pull request closed without merging**
