### PR TITLE
[WIP] Support associations and embeds

### PR DESCRIPTION
**Pull request by narrowtux**
**This is a WIP Pull Request** it is only made this early to allow discussion about the code

## TODO

- [x] function that extracts a flat list of version structs
- [x] make insert work
- [ ] make insert work (strict mode)
- [x] make insert! work
- [x] make update work
- [ ] make update work (strict mode)
- [x] make update! work
- [x] check if delete needs to be handled too
- [x] before deleting, perform some schema reflection magic to get a list of the assocs that would be deleted too
- [x] also check child assocs that have `on_delete: :nillify_all` so those get a version record that the reference was set to null
- [x] reduce changesets to a simple map when not using UUID keys
- [ ] otherwise, create version records for embeds as well (should work by reusing the assoc code)
  - [x] insert, update
  - [ ] delete

### CODE REVIEW

**Comment by narrowtux** [comment]
@izelnakri I've got some more tests to write, clean up a few things and also implement strict mode (as soon as I understand what it does exactly), but otherwise, it looks like it's going to work really well.

**Comment by izelnakri** [comment]
@narrowtux thanks for all the work you've done so far and the TODOs that make the PR more understandable! Could you explain to me what this is for: "reduce changesets to a simple map when not using UUID keys" ?

**Comment by narrowtux** [comment]
Embeds use UUID keys by default, since ecto has to generate them and not a DB. That saves them from having to implement some kind of auto increment logic without a database (nearly impossible).

So if someone is using UUID keys, we can store actual versions for each embed in the normal versions table. If not, the embeds have to be handled in a special way so that PaperTrail doesn't crash when updating a struct in the DB that has an updated embed inside.

**Comment by johnhamelink** [comment]
@narrowtux I'd love to see this added to paper_trail - do you plan on finishing this PR? I may be able to help you in the coming weeks/months.

**Comment by narrowtux** [comment]
Sorry I kinda gave up on this, there was too much work to be done and every time I wanted to tackle an issue a rabbit hole of new issues opened. It has become clear to me that this project wasn't what I wanted it to be, which is fine, but I couldn't use it in our product.

So in the end, I decided to write my own audit/history/revert library, don't want to plug it here though.

**Comment by paranojik** [comment]
I'm continuing the work on this in #60

**Comment by izelnakri** [comment]
Closing this PR due to inactivity, please ping me when/if its ready to be reopened.

**Pull request closed without merging**
