### PR TITLE
Originator support

### PR DESCRIPTION
**Pull request by asiniy**
WIP

- [x] Ability so specify originator
- [x] Migration with originator specified
- [x] Functionality
- [ ] Tests
- [x] README

### CODE REVIEW

**Comment by asiniy** [comment]
@izelnakri it's ready and well tested.
I don't know how to write automatic tests cuz test suite is too coupled.

**Comment by izelnakri** [comment]
very interesting PR, thank you for contributing! I'll evaluate it soon, didn't read your originator assignment logic well enough yet.

**Comment by asiniy** [comment]
@izelnakri ?

**Comment by izelnakri** [comment]
could you write some tests for the following scenarios as well:

"when there is no originator, version can be inserted"

"when there is an invalid originator, version can't be inserted"

"when there is a valid originator, version can be inserted with valid originator reference/relationship"

**Comment by asiniy** [comment]
@izelnakri will do

**Comment by izelnakri** [comment]
Hi @asiniy, I've implemented this feature along with many other features part of the 0.6.0 release. Sorry for not merging this branch wasnt sure about the naming first but finally decided originator is the right naming. I'll mention you in the credits part of the README.md for your contribution along with others. Thanks again for contributing, feel free to provide your ideas & improvements like these in future!

**Pull request closed without merging**
